#Add values for any properties you wish to change when deploying the Trading Partner.
#Delete any lines that you don't want to update.
#FlexDeploy properties or plain text are allowed.
#See the documentation at https://wiki.flexagon.com for more information.


######################## ACME_TRADING_PARTNER ########################

# Transports
# ACME_TP1
# Receive
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.LIST_PhysicalDirectory=/pub/
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.Recursive=false
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.IncludeFilesWildCard=*
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.MinimumAge=0
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.MaxRaiseSize=100
# Send
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.WRITE_PhysicalDirectory=/pub/
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.FileNamingConvention=order_%SEQ%.dat

# ACME_TP2
# Send
ACME_TRADING_PARTNER.transports.ACME_TP20AF42BE41A11AF3CB72000003477DC16.SEND_REST_URI=/test

# ACME_TP3
# AS2 identifiers
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.host_as2_id=FLEXAGONOIC_AS2
# Receive
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.allowAnyAs2Identifier=true
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.dontValidateAS2ToHeader=true
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.isForcedSignVerificationInbound=false
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.isForcedEncryptionCheckInbound=false
# Send
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.message_subject=test
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.payload_content_type=
# Packaging options
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.sign_algo=SMIME 3.2 with SHA1-RSA
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.encrypt_algo=SMIME-3_0-RC2-40
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.signCompressOrder=NONE
# MDN options
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.mdn_return_method=Sync
ACME_TRADING_PARTNER.transports.ACME_TP30AF417EC1A11AF8789700000703740A5.signed_mdn=false

# ACME_TP4
# AS4 identifiers
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.host_as4_id=RGT
# Send
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.payload_content_type=application/EDI-Consent
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.pmode_id=test
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.pmode_agreementref=test4
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.send_payload_as_attachment=true
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.usePasswordDigestForOutbound=false
# Packaging options
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.sign_algo=RSA_SHA1
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.encrypt_algo=TRIPLE_DES
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.isCompressed=false
# MDN options
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.mdn_return_method=Sync
ACME_TRADING_PARTNER.transports.ACME_TP40AF417EC1A11AF9C3B800000703740A7.signed_mdn=false

# ACME_TP5
# RosettaNet identifiers
ACME_TRADING_PARTNER.transports.ACME_TP50AF42BE41A11B001756000003477DC18.host_duns_id=this2
# Send
ACME_TRADING_PARTNER.transports.ACME_TP50AF42BE41A11B001756000003477DC18.additional_transport_headers=dd
# Packaging options
ACME_TRADING_PARTNER.transports.ACME_TP50AF42BE41A11B001756000003477DC18.sign_algo=NONE
ACME_TRADING_PARTNER.transports.ACME_TP50AF42BE41A11B001756000003477DC18.encrypt_algo=NONE
ACME_TRADING_PARTNER.transports.ACME_TP50AF42BE41A11B001756000003477DC18.signCompressOrder=NONE

# OutboundAgreements
# ACME_OUTBOUND_AGREEMENT
# Host identifiers
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.hostIdentifiers.1=Application Partner ID | RG
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.hostIdentifiers.1=Application Partner ID | RGT
# Configure agreement settings
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.validate=true
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.acceptGroup=
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.acceptGroupName=
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.rejectGroup=
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.rejectGroupName=
# Generate functional acknowledgment
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.fa=true

# InboundAgreements
# ACME_INBOUND_AGREEMENT
# Configure agreement settings
ACME_TRADING_PARTNER.inboundAgreements.ACME_INBOUND_AGREEMENT1787223670033.validate=true
ACME_TRADING_PARTNER.inboundAgreements.ACME_INBOUND_AGREEMENT1787223670033.acceptGroup=
ACME_TRADING_PARTNER.inboundAgreements.ACME_INBOUND_AGREEMENT1787223670033.acceptGroupName=
ACME_TRADING_PARTNER.inboundAgreements.ACME_INBOUND_AGREEMENT1787223670033.rejectGroup=
ACME_TRADING_PARTNER.inboundAgreements.ACME_INBOUND_AGREEMENT1787223670033.rejectGroupName=
# Generate functional acknowledgment
ACME_TRADING_PARTNER.inboundAgreements.ACME_INBOUND_AGREEMENT1787223670033.fa=true
ACME_TRADING_PARTNER.inboundAgreements.ACME_INBOUND_AGREEMENT1787223670033.duplicateCtrlNumCheck=false


##############################################################
