#Add values for any properties you wish to change when updating B2B Trading Partner Identifiers.
#Delete any lines that you don't want to update values.
#FlexDeploy properties or plain text are allowed.
See the documentation at https://wiki.flexagon.com for more information.


######################## AVINSH_CORP ########################

AVINSH_CORP.36990536471679.AS2 Identifier=test01
AVINSH_CORP.531584087610037.AS2 Identifier=AVN corp2

##############################################################

######################## MUTHUCORP ########################

MUTHUCORP.2892859221053846.EDI Interchange ID Qualifier=ZZ
MUTHUCORP.2892859221078744.AS2 Identifier=MUTHUCORP_AS2

##############################################################

######################## RAJ_B2B_TEST:RAJ_TRADING_PARTNER ########################

RAJ_B2B_TEST:RAJ_TRADING_PARTNER.604500079445274.Name=av

##############################################################
