#Add values for any properties you wish to change when deploying the Trading Partner.
#Delete any lines that you don't want to update.
#FlexDeploy properties or plain text are allowed.
#See the documentation at https://wiki.flexagon.com for more information.


######################## ACME_TRADING_PARTNER ########################

# Transports
# ACME_TP1
# Receive
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.LIST_PhysicalDirectory=/pub/example5
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.Recursive=false
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.IncludeFilesWildCard=*
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.MinimumAge=0
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.MaxRaiseSize=100
# Send
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.WRITE_PhysicalDirectory=/pub/example
ACME_TRADING_PARTNER.transports.ACME_TP10AF408301A01F81323000000643EABCA.FileNamingConvention=order_%SEQ%.dat

# ACME_TP2

# outboundAgreements - Host identifiers
# ACME_OUTBOUND_AGREEMENT
ACME_TRADING_PARTNER.outboundAgreements.ACME_OUTBOUND_AGREEMENT1787223755223.hostIdentifiers.Application Partner ID=SUPPLIER_T


##############################################################
