#Add values for any properties you wish to change when updating B2B Trading Partner Identifiers.
#Delete any lines that you don't want to update values.
#FlexDeploy properties or plain text are allowed.
#See the documentation at https://wiki.flexagon.com for more information.


######################## ACME_TRADING_PARTNER ########################

ACME_TRADING_PARTNER.5368095945665594.AS2 Identifier=ACME_AS2_ID

#Control Numbers
ACME_TRADING_PARTNER.interchangeControlNumberStart=
ACME_TRADING_PARTNER.groupControlNumberStart=
ACME_TRADING_PARTNER.transactionControlNumberStart=

##############################################################
